weights: yolov5s.pt
cfg: ./yolov5x.yaml
data: ./data.yaml
hyp: data/hyp.scratch.yaml
epochs: 5
batch_size: 16
img_size:
- 640
- 640
world_size: 1
global_rank: -1
resume: false
name: test_yolov5x
evolve: false
project: runs/train
exist_ok: false
save_dir: runs/train/exp
total_batch_size: 16
device: ''
local_rank: -1
single_cls: false
adam: false
linear_lr: false
sync_bn: false
cache_images: false
rect: false
workers: 8
image_weights: false
quad: false
noautoanchor: false
multi_scale: false
notest: false
bucket: ''
nosave: false